#pragma once

extern const char* const MEVACOIN_VERSION_TAG;
extern const char* const MEVACOIN_VERSION;
extern const char* const MEVACOIN_RELEASE_NAME;
extern const char* const MEVACOIN_VERSION_FULL;
extern const bool MEVACOIN_VERSION_IS_RELEASE;

// Compatibilità con il codice che usa ancora MEVACOIN_*
#define MEVACOIN_VERSION_TAG      MEVACOIN_VERSION_TAG
#define MEVACOIN_VERSION          MEVACOIN_VERSION
#define MEVACOIN_RELEASE_NAME     MEVACOIN_RELEASE_NAME
#define MEVACOIN_VERSION_FULL     MEVACOIN_VERSION_FULL
#define MEVACOIN_VERSION_IS_RELEASE MEVACOIN_VERSION_IS_RELEASE
