name: Build Boost Android ARM64

on:
  workflow_dispatch:   # Avvio manuale dal tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r23c
      BOOST_VERSION: 1.82.0
      BOOST_VERSION_UNDERSCORE: 1_82_0
      ANDROID_API: 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar bzip2 build-essential python3 cmake

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          unzip android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          mv android-ndk-${ANDROID_NDK_VERSION} $HOME/android-ndk
          echo "NDK path: $HOME/android-ndk"

      - name: Download Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2
          tar xjf boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2

      - name: Build Boost for Android ARM64
        run: |
          cd boost_${BOOST_VERSION_UNDERSCORE}
          ./bootstrap.sh
          ./b2 toolset=clang-arm64 target-os=android threading=multi link=static runtime-link=static \
              cxxflags="-std=c++14" \
              --prefix=$HOME/boost-android install

      - name: Upload Boost artifacts
        uses: actions/upload-artifact@v3
        with:
          name: boost-android
          path: $HOME/boost-android
