name: Build Mevacoin Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set BOOST_ROOT
      run: |
        set "BOOST_ROOT=C:\boost"
        echo BOOST_ROOT=%BOOST_ROOT%
      shell: cmd

    - name: Download precompiled Boost 1.89
      run: |
        curl -L -o boost.exe https://downloads.sourceforge.net/project/boost/boost-binaries/1.89.0/boost_1_89_0-msvc-14.3-64.exe
        mkdir C:\boost
        Start-Process -FilePath .\boost.exe -ArgumentList "-y","-oC:\boost" -Wait
      shell: powershell

    - name: Set up Visual Studio environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

    - name: Configure CMake
      shell: cmd
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DBOOST_ROOT=C:\boost

    - name: Build Mevacoin
      shell: cmd
      run: cmake --build build --config Release

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mevacoin-windows
        path: build/Release/
