name: Build Mevacoin for Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Scarica Boost precompilato (ZIP)
      - name: Download Boost prebuilt binaries
        run: |
          curl -L -o boost.zip https://sourceforge.net/projects/boost/files/boost-binaries/1.86.0/boost_1_86_0-msvc-14.3-64.exe/download
          Rename-Item boost.zip boost.exe
          Start-Process -FilePath .\boost.exe -ArgumentList "-y","-oC:\boost" -Wait
        shell: pwsh

      # 3️⃣ Imposta variabile BOOST_ROOT
      - name: Set BOOST_ROOT
        run: echo "BOOST_ROOT=C:\boost" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # 4️⃣ Installa CMake
      - name: Install CMake
        uses: lukka/get-cmake@latest

      # 5️⃣ Configura il progetto
      - name: Configure Mevacoin with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DBOOST_ROOT=C:\boost

      # 6️⃣ Compila il progetto
      - name: Build Mevacoin
        run: cmake --build build --config Release

      # 7️⃣ Salva gli eseguibili come artefatti
      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: Mevacoin-Windows
          path: build/**/*.exe
